package provider

import (
	"context"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"

	"github.com/hashicorp/terraform-plugin-framework/providerserver"
	"github.com/hashicorp/terraform-plugin-go/tfprotov6"
)

var updateSchemaSnapshot = flag.Bool("update", false, "rewrite the schema snapshot instead of comparing against it")

const schemaSnapshotPath = "testdata/schema.txt"

// TestSchemaSnapshot pins the shape of every resource and data source schema.
//
// It exists for state compatibility rather than for style. Terraform stores state
// against the schema that wrote it, so removing an attribute, renaming one, or
// changing its type breaks anyone holding state written by an earlier version unless
// the resource's schema Version is raised and an UpgradeState is supplied. Before the
// first published release that is free; afterwards it is a promise. Nothing in the
// framework reminds you which side of that line you are on, so this test does: any
// change to a schema's shape fails here, and the diff says exactly what moved.
//
// Descriptions are deliberately excluded. They are rewritten often, they never break
// state, and including them would train everyone to re-approve the snapshot without
// reading it - which is how a real change slips through.
//
// Run `go test ./internal/provider/ -update` to accept an intended change, then read
// the diff in the commit as carefully as you would read the code.
func TestSchemaSnapshot(t *testing.T) {
	factory := providerserver.NewProtocol6WithError(New("test")())
	server, err := factory()
	if err != nil {
		t.Fatalf("building the provider server: %v", err)
	}

	response, err := server.GetProviderSchema(context.Background(), &tfprotov6.GetProviderSchemaRequest{})
	if err != nil {
		t.Fatalf("GetProviderSchema: %v", err)
	}

	// A schema the framework rejects comes back as diagnostics plus empty maps, not as
	// an error. Without this check the snapshot would render as almost nothing and the
	// comparison would report a puzzling difference on line 12 rather than the actual
	// complaint, which is exactly what happened the first time this test was tried.
	for _, d := range response.Diagnostics {
		if d.Severity == tfprotov6.DiagnosticSeverityError {
			t.Fatalf("the provider rejected its own schema: %s\n%s", d.Summary, d.Detail)
		}
	}

	got := renderProviderSchema(response)

	if *updateSchemaSnapshot {
		if err := os.MkdirAll(filepath.Dir(schemaSnapshotPath), 0o755); err != nil {
			t.Fatalf("creating the snapshot directory: %v", err)
		}
		if err := os.WriteFile(schemaSnapshotPath, []byte(got), 0o644); err != nil {
			t.Fatalf("writing the snapshot: %v", err)
		}
		t.Logf("snapshot rewritten: %s", schemaSnapshotPath)

		return
	}

	want, err := os.ReadFile(schemaSnapshotPath)
	if err != nil {
		t.Fatalf("reading the snapshot: %v\n\nCreate it with: go test ./internal/provider/ -update", err)
	}

	if string(want) == got {
		return
	}

	t.Errorf("provider schema no longer matches %s.\n\n%s\n\n"+
		"If this change is intended, it is a schema change: check whether it removes, renames or "+
		"retypes anything a stored state could hold. If it does and a release has already gone out, "+
		"raise the resource's schema Version and add an UpgradeState before accepting this. "+
		"Then run: go test ./internal/provider/ -update",
		schemaSnapshotPath, firstDifference(string(want), got))
}

// firstDifference reports the first differing line with a little context, which is
// more useful in a test log than a whole-file dump of a large schema.
func firstDifference(want, got string) string {
	wantLines, gotLines := strings.Split(want, "\n"), strings.Split(got, "\n")

	for i := 0; i < len(wantLines) || i < len(gotLines); i++ {
		w, g := "", ""
		if i < len(wantLines) {
			w = wantLines[i]
		}
		if i < len(gotLines) {
			g = gotLines[i]
		}
		if w == g {
			continue
		}

		var b strings.Builder
		fmt.Fprintf(&b, "first difference at line %d:\n", i+1)
		for j := max(0, i-3); j < i; j++ {
			fmt.Fprintf(&b, "  %s\n", wantLines[j])
		}
		fmt.Fprintf(&b, "- want: %s\n", w)
		fmt.Fprintf(&b, "+ got:  %s\n", g)

		return b.String()
	}

	return "files differ only in trailing content"
}

// renderProviderSchema writes the schema out in a stable, readable form. Everything
// is sorted, so the file only changes when the schema does.
func renderProviderSchema(response *tfprotov6.GetProviderSchemaResponse) string {
	var b strings.Builder

	b.WriteString("# Shape of every schema this provider serves. Generated by\n")
	b.WriteString("# TestSchemaSnapshot; see its comment before accepting a change.\n")

	if response.Provider != nil {
		b.WriteString("\nprovider\n")
		writeBlock(&b, response.Provider, "  ")
	}

	writeSchemaSet(&b, "resource", response.ResourceSchemas)
	writeSchemaSet(&b, "data source", response.DataSourceSchemas)

	return b.String()
}

func writeSchemaSet(b *strings.Builder, kind string, schemas map[string]*tfprotov6.Schema) {
	names := make([]string, 0, len(schemas))
	for name := range schemas {
		names = append(names, name)
	}
	sort.Strings(names)

	for _, name := range names {
		fmt.Fprintf(b, "\n%s %s\n", kind, name)
		writeBlock(b, schemas[name], "  ")
	}
}

func writeBlock(b *strings.Builder, schema *tfprotov6.Schema, indent string) {
	// The version is the whole point of the file: it is what an UpgradeState keys off.
	fmt.Fprintf(b, "%sschema version %d\n", indent, schema.Version)
	if schema.Block == nil {
		return
	}

	writeBlockBody(b, schema.Block, indent)
}

func writeBlockBody(b *strings.Builder, block *tfprotov6.SchemaBlock, indent string) {
	attrs := append([]*tfprotov6.SchemaAttribute(nil), block.Attributes...)
	sort.Slice(attrs, func(i, j int) bool { return attrs[i].Name < attrs[j].Name })

	for _, attr := range attrs {
		fmt.Fprintf(b, "%s%s %s%s\n", indent, attr.Name, attributeType(attr), flags(attr))
		if attr.NestedType != nil {
			writeObject(b, attr.NestedType, indent+"  ")
		}
	}

	blocks := append([]*tfprotov6.SchemaNestedBlock(nil), block.BlockTypes...)
	sort.Slice(blocks, func(i, j int) bool { return blocks[i].TypeName < blocks[j].TypeName })

	for _, nested := range blocks {
		fmt.Fprintf(b, "%sblock %s (%s)\n", indent, nested.TypeName, nestingMode(nested.Nesting))
		if nested.Block != nil {
			writeBlockBody(b, nested.Block, indent+"  ")
		}
	}
}

func writeObject(b *strings.Builder, object *tfprotov6.SchemaObject, indent string) {
	attrs := append([]*tfprotov6.SchemaAttribute(nil), object.Attributes...)
	sort.Slice(attrs, func(i, j int) bool { return attrs[i].Name < attrs[j].Name })

	for _, attr := range attrs {
		fmt.Fprintf(b, "%s%s %s%s\n", indent, attr.Name, attributeType(attr), flags(attr))
		if attr.NestedType != nil {
			writeObject(b, attr.NestedType, indent+"  ")
		}
	}
}

func attributeType(attr *tfprotov6.SchemaAttribute) string {
	if attr.Type == nil {
		// A nested-object attribute carries its shape in NestedType instead.
		return "object(" + nestingMode(attr.NestedType.Nesting) + ")"
	}

	return attr.Type.String()
}

func flags(attr *tfprotov6.SchemaAttribute) string {
	var set []string
	if attr.Required {
		set = append(set, "required")
	}
	if attr.Optional {
		set = append(set, "optional")
	}
	if attr.Computed {
		set = append(set, "computed")
	}
	if attr.Sensitive {
		set = append(set, "sensitive")
	}
	if len(set) == 0 {
		return ""
	}

	return " [" + strings.Join(set, " ") + "]"
}

func nestingMode(mode any) string {
	return fmt.Sprintf("%v", mode)
}
